import { ArrowUpRight, AtSign, CalendarDays, Check, ChevronRight, Clock3, MapPin, Phone, Scissors, Sparkles, Star } from "lucide-react";
const booking="https://apps.apple.com/br/app/sky-barbearia/id6752877283", instagram="https://instagram.com/barbeariasky", maps="https://www.google.com/maps/search/?api=1&query=R.+Juvenal+Mário+da+Silva,+285,+Manaíra,+João+Pessoa+-+PB";
const services=[
 {n:"01",title:"Corte & estilo",text:"Técnica, acabamento e orientação para um corte que funcione com sua rotina."},
 {n:"02",title:"Visagismo",text:"Uma leitura individual de traços, personalidade e imagem para escolhas mais conscientes."},
 {n:"03",title:"Barba",text:"Desenho, alinhamento e cuidado para valorizar os contornos do rosto."},
 {n:"04",title:"Prótese capilar",text:"Avaliação especializada e atendimento cuidadoso para renovar confiança e naturalidade."},
 {n:"05",title:"Spa do Noivo",text:"Um ritual de preparação pensado para viver o grande dia com presença e tranquilidade."},
 {n:"06",title:"SKY Kids",text:"Atendimento acolhedor e paciente para que os pequenos também aproveitem a experiência."}];
const reviews=[["Gabriel Carulla","Atendimento excelente. Acertou no corte e a experiência fazendo a barba foi tão relaxante que cochilei."],["Tatiana Soares","O corte ficou exatamente como eu queria, com muito capricho e qualidade. Ambiente muito limpo."],["Yanna Motta","Levei minha filha para fazer um corte curtinho. O profissional foi super atencioso e fez um excelente trabalho."]];
export default function Home(){return <main>
 <header className="nav shell"><a className="brand" href="#inicio" aria-label="SKY Barbearia — início"><span>SKY</span><small>BARBEARIA</small></a><nav aria-label="Navegação principal"><a href="#servicos">Serviços</a><a href="#experiencia">Experiência</a><a href="#avaliacoes">Avaliações</a><a href="#contato">Contato</a></nav><a className="button button-sm" href={booking} target="_blank">Agendar <ArrowUpRight size={16}/></a></header>
 <section className="hero" id="inicio"><div className="hero-photo" aria-hidden="true"/><div className="hero-shade"/><div className="hero-content shell"><p className="eyebrow"><span/>Especialista em visagismo na Paraíba</p><h1>Seu estilo,<br/><em>com intenção.</em></h1><p className="lead">Mais do que um corte: uma experiência criada para revelar sua identidade, renovar sua confiança e cuidar de cada detalhe.</p><div className="hero-actions"><a className="button" href={booking} target="_blank"><CalendarDays size={18}/> Agendar experiência</a><a className="text-link" href="#servicos">Conhecer serviços <ChevronRight size={18}/></a></div></div><div className="proof"><strong>5,0 <Star size={17} fill="currentColor"/></strong><span>Excelência comprovada por<br/>mais de 1.900 avaliações</span></div></section>
 <section className="intro shell" id="experiencia"><div><p className="eyebrow dark"><span/>A experiência SKY</p><h2>Você não precisa caber em um estilo.<br/><em>O estilo precisa caber em você.</em></h2></div><div className="intro-copy"><p>Na SKY, cada atendimento começa entendendo quem você é. Técnica e visagismo se encontram para construir uma imagem autêntica — sem fórmulas prontas.</p><div className="checks"><span><Check/>Atendimento personalizado</span><span><Check/>Ambiente limpo e acolhedor</span><span><Check/>Profissionais especializados</span></div></div></section>
 <section className="services" id="servicos"><div className="shell"><div className="section-head"><div><p className="eyebrow"><span/>Nossos serviços</p><h2>Cuidado completo.<br/><em>Resultado singular.</em></h2></div><p>Do clássico ao contemporâneo, cada serviço é conduzido com precisão, escuta e respeito à sua identidade.</p></div><div className="service-grid">{services.map(s=><article key={s.n}><span>{s.n}</span><div className="service-icon">{s.n==="02"?<Sparkles/>:<Scissors/>}</div><h3>{s.title}</h3><p>{s.text}</p><a href={booking} target="_blank">Agendar este serviço <ArrowUpRight size={15}/></a></article>)}</div></div></section>
 <section className="visagismo shell"><div className="portrait" role="img" aria-label="Ambiente interno da SKY Barbearia"/><div className="visagismo-copy"><p className="eyebrow dark"><span/>Nosso diferencial</p><h2>Visagismo é quando<br/>a imagem <em>fala por você.</em></h2><p>Formato do rosto, textura do cabelo, estilo de vida e a mensagem que você quer transmitir. Tudo entra na conversa antes da primeira tesourada.</p><div className="steps"><span><b>01</b>Escuta e diagnóstico</span><span><b>02</b>Proposta personalizada</span><span><b>03</b>Execução e orientação</span></div><a className="button dark-button" href={instagram} target="_blank">Conheça nosso trabalho <AtSign size={17}/></a></div></section>
 <section className="reviews" id="avaliacoes"><div className="shell"><div className="rating"><p className="eyebrow"><span/>Quem vive, recomenda</p><strong>5,0</strong><div className="stars">★★★★★</div><p>1.922 avaliações no Google</p></div><div className="review-list">{reviews.map(([name,text])=><blockquote key={name}><div className="stars">★★★★★</div><p>“{text}”</p><footer><span>{name[0]}</span><div><strong>{name}</strong><small>Cliente SKY · Google</small></div></footer></blockquote>)}</div></div></section>
 <section className="contact shell" id="contato"><div><p className="eyebrow dark"><span/>Visite a SKY</p><h2>Seu próximo estilo<br/>começa <em>aqui.</em></h2><p className="contact-lead">Estamos no coração de Manaíra, em um espaço preparado para receber você.</p></div><div className="contact-card"><div><MapPin/><p><strong>Center Dois Mil — Sala 107</strong>R. Juvenal Mário da Silva, 285<br/>Manaíra, João Pessoa — PB</p></div><div><Clock3/><p><strong>Horário de funcionamento</strong>Segunda a sábado · 09h às 19h<br/>Domingo · Fechado</p></div><div><Phone/><p><strong>Fale com a SKY</strong>(83) 3021-5895</p></div><div className="contact-actions"><a className="button" href={maps} target="_blank">Como chegar <MapPin size={17}/></a><a href="tel:+558330215895">Ligar agora</a></div></div></section>
 <footer><div className="shell footer-grid"><div className="brand"><span>SKY</span><small>BARBEARIA</small></div><p>Especialista em visagismo, prótese capilar<br/>e cuidado masculino em João Pessoa.</p><a href={instagram} target="_blank"><AtSign/> barbeariasky</a></div><div className="shell footnote"><span>© 2026 SKY Barbearia</span><span>Manaíra · João Pessoa · Paraíba</span></div></footer>
 </main>}
